import Head from 'next/head'
import Product from '../../product/[id]'

export default function Home() {
  return (
    <>
      <Head>
        <title>PROJECT ZOMBOID </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main /* className={styles.main} */>
       <h1>josiel </h1>
       <Product />
       
      
      </main>
    </>
  )
}
